export const monacoThemes = [
    'Active4D',
    'All Hallows Eve',
    'Amy',
    'Birds of Paradise',
    'Blackboard',
    'Brilliance Black',
    'Brilliance Dull',
    'Chrome DevTools',
    'Clouds Midnight',
    'Clouds',
    'Cobalt',
    'Dawn',
    'Dominion Day',
    'Dreamweaver',
    'Eiffel',
    'Espresso Libre',
    'GitHub',
    'IDLE',
    'Katzenmilch',
    'Kuroir Theme',
    'LAZY',
    'MagicWB (Amiga)',
    'Merbivore Soft',
    'Merbivore',
    'Monokai Bright',
    'Monokai',
    'Night Owl',
    'Oceanic Next',
    'Pastels on Dark',
    'Slush and Poppies',
    'Solarized-dark',
    'Solarized-light',
    'SpaceCadet',
    'Sunburst',
    'Textmate (Mac Classic)',
    'Tomorrow-Night-Blue',
    'Tomorrow-Night-Bright',
    'Tomorrow-Night-Eighties',
    'Tomorrow-Night',
    'Tomorrow',
    'Twilight',
    'Upstream Sunburst',
    'Vibrant Ink',
    'Xcode_default',
    'Zenburnesque',
    'iPlastic',
    'idleFingers',
    'krTheme',
    'monoindustrial',
    'themelist',
];
